//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarframeTileDirectory.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarframeTileDirectory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeeklyPuzzle,Maroo Ayatan Hunt
        ///TRRace,Rush (Archwing)
        ///TRSabotage,Sabotage (Archwing)
        ///TRMobileDefense,Mobile Defense (Archwing)
        ///TRExterminate,Exterminate (Archwing)
        ///Pursuit,Pursuit (Archwing)
        ///MobileDefenseProcLevel,Mobile Defense (Archwing)
        ///InterceptionProcLevel,Interception (Archwing)
        ///ExterminateProcLevel,Exterminate (Archwing)
        ///BossVor,Assassination (Vor)
        ///JackalBoss,Assassination (Jackal)
        ///GrineerForestBoss,Assassination (Vay Hek)
        ///GrineerSettlementBoss,Assassination (Lech Kril)
        ///GrineerShipyardsA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MissionNames {
            get {
                return ResourceManager.GetString("MissionNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VenusLandscape
        ///SolarisUnitedTown
        ///RelayStationHub
        ///Prefabs
        ///ClanDojo
        ///OstronTown
        ///EidolonLandscape
        ///PVP
        ///TennoJunction
        ///Arena
        ///SentientQuest
        ///MoonQuest
        ///TnoDioramaCephalonA.
        /// </summary>
        internal static string nonProcedualSets {
            get {
                return ResourceManager.GetString("nonProcedualSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CorpusGasCity
        ///CorpusIcePlanet
        ///CorpusOutpost
        ///InfestedCorpusShip
        ///CorpusShip
        ///CorpusToGrineer
        ///GrineerAsteroid
        ///GrineerForest
        ///GrineerFortress
        ///GrineerGalleon
        ///GrineerOcean
        ///GrineerSettlement
        ///GrineerShipyards
        ///GrineerToCorpus
        ///OrokinTowerDerelict
        ///OrokinMoon
        ///OrokinTower
        ///.
        /// </summary>
        internal static string TilesetNames {
            get {
                return ResourceManager.GetString("TilesetNames", resourceCulture);
            }
        }
    }
}
